package main

import (
	"github.com/amazon-workspaces/mcp-server/config"
	"github.com/amazon-workspaces/mcp-server/models"
	tools_x_amz_target_workspacesservice_createworkspacebundle "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createworkspacebundle"
	tools_x_amz_target_workspacesservice_modifyclientproperties "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifyclientproperties"
	tools_x_amz_target_workspacesservice_modifyworkspacecreationproperties "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifyworkspacecreationproperties"
	tools_x_amz_target_workspacesservice_describeworkspacesconnectionstatus "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeworkspacesconnectionstatus"
	tools_x_amz_target_workspacesservice_updateworkspacebundle "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_updateworkspacebundle"
	tools_x_amz_target_workspacesservice_authorizeiprules "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_authorizeiprules"
	tools_x_amz_target_workspacesservice_describeconnectionaliaspermissions "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeconnectionaliaspermissions"
	tools_x_amz_target_workspacesservice_deleteconnectionalias "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deleteconnectionalias"
	tools_x_amz_target_workspacesservice_describeipgroups "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeipgroups"
	tools_x_amz_target_workspacesservice_rebootworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_rebootworkspaces"
	tools_x_amz_target_workspacesservice_deletetags "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deletetags"
	tools_x_amz_target_workspacesservice_copyworkspaceimage "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_copyworkspaceimage"
	tools_x_amz_target_workspacesservice_importworkspaceimage "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_importworkspaceimage"
	tools_x_amz_target_workspacesservice_createconnectclientaddin "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createconnectclientaddin"
	tools_x_amz_target_workspacesservice_modifyworkspaceproperties "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifyworkspaceproperties"
	tools_x_amz_target_workspacesservice_modifyworkspacestate "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifyworkspacestate"
	tools_x_amz_target_workspacesservice_createupdatedworkspaceimage "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createupdatedworkspaceimage"
	tools_x_amz_target_workspacesservice_createworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createworkspaces"
	tools_x_amz_target_workspacesservice_describeaccount "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeaccount"
	tools_x_amz_target_workspacesservice_createworkspaceimage "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createworkspaceimage"
	tools_x_amz_target_workspacesservice_modifyworkspaceaccessproperties "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifyworkspaceaccessproperties"
	tools_x_amz_target_workspacesservice_describeworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeworkspaces"
	tools_x_amz_target_workspacesservice_describeclientbranding "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeclientbranding"
	tools_x_amz_target_workspacesservice_startworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_startworkspaces"
	tools_x_amz_target_workspacesservice_createstandbyworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createstandbyworkspaces"
	tools_x_amz_target_workspacesservice_importclientbranding "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_importclientbranding"
	tools_x_amz_target_workspacesservice_deleteipgroup "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deleteipgroup"
	tools_x_amz_target_workspacesservice_revokeiprules "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_revokeiprules"
	tools_x_amz_target_workspacesservice_updateconnectclientaddin "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_updateconnectclientaddin"
	tools_x_amz_target_workspacesservice_deleteconnectclientaddin "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deleteconnectclientaddin"
	tools_x_amz_target_workspacesservice_describeconnectionaliases "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeconnectionaliases"
	tools_x_amz_target_workspacesservice_describeworkspacebundles "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeworkspacebundles"
	tools_x_amz_target_workspacesservice_migrateworkspace "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_migrateworkspace"
	tools_x_amz_target_workspacesservice_deleteworkspacebundle "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deleteworkspacebundle"
	tools_x_amz_target_workspacesservice_listavailablemanagementcidrranges "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_listavailablemanagementcidrranges"
	tools_x_amz_target_workspacesservice_modifycertificatebasedauthproperties "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifycertificatebasedauthproperties"
	tools_x_amz_target_workspacesservice_deleteworkspaceimage "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deleteworkspaceimage"
	tools_x_amz_target_workspacesservice_rebuildworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_rebuildworkspaces"
	tools_x_amz_target_workspacesservice_registerworkspacedirectory "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_registerworkspacedirectory"
	tools_x_amz_target_workspacesservice_modifyselfservicepermissions "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifyselfservicepermissions"
	tools_x_amz_target_workspacesservice_describetags "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describetags"
	tools_x_amz_target_workspacesservice_stopworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_stopworkspaces"
	tools_x_amz_target_workspacesservice_describeworkspacesnapshots "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeworkspacesnapshots"
	tools_x_amz_target_workspacesservice_modifysamlproperties "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifysamlproperties"
	tools_x_amz_target_workspacesservice_describeworkspaceimagepermissions "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeworkspaceimagepermissions"
	tools_x_amz_target_workspacesservice_modifyaccount "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_modifyaccount"
	tools_x_amz_target_workspacesservice_associateipgroups "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_associateipgroups"
	tools_x_amz_target_workspacesservice_describeworkspacedirectories "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeworkspacedirectories"
	tools_x_amz_target_workspacesservice_deregisterworkspacedirectory "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deregisterworkspacedirectory"
	tools_x_amz_target_workspacesservice_describeclientproperties "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeclientproperties"
	tools_x_amz_target_workspacesservice_updateworkspaceimagepermission "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_updateworkspaceimagepermission"
	tools_x_amz_target_workspacesservice_describeaccountmodifications "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeaccountmodifications"
	tools_x_amz_target_workspacesservice_createtags "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createtags"
	tools_x_amz_target_workspacesservice_terminateworkspaces "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_terminateworkspaces"
	tools_x_amz_target_workspacesservice_deleteclientbranding "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_deleteclientbranding"
	tools_x_amz_target_workspacesservice_disassociateipgroups "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_disassociateipgroups"
	tools_x_amz_target_workspacesservice_createconnectionalias "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createconnectionalias"
	tools_x_amz_target_workspacesservice_updaterulesofipgroup "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_updaterulesofipgroup"
	tools_x_amz_target_workspacesservice_restoreworkspace "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_restoreworkspace"
	tools_x_amz_target_workspacesservice_disassociateconnectionalias "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_disassociateconnectionalias"
	tools_x_amz_target_workspacesservice_describeworkspaceimages "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeworkspaceimages"
	tools_x_amz_target_workspacesservice_createipgroup "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_createipgroup"
	tools_x_amz_target_workspacesservice_associateconnectionalias "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_associateconnectionalias"
	tools_x_amz_target_workspacesservice_describeconnectclientaddins "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_describeconnectclientaddins"
	tools_x_amz_target_workspacesservice_updateconnectionaliaspermission "github.com/amazon-workspaces/mcp-server/tools/x_amz_target_workspacesservice_updateconnectionaliaspermission"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_workspacesservice_createworkspacebundle.CreateCreateworkspacebundleTool(cfg),
		tools_x_amz_target_workspacesservice_modifyclientproperties.CreateModifyclientpropertiesTool(cfg),
		tools_x_amz_target_workspacesservice_modifyworkspacecreationproperties.CreateModifyworkspacecreationpropertiesTool(cfg),
		tools_x_amz_target_workspacesservice_describeworkspacesconnectionstatus.CreateDescribeworkspacesconnectionstatusTool(cfg),
		tools_x_amz_target_workspacesservice_updateworkspacebundle.CreateUpdateworkspacebundleTool(cfg),
		tools_x_amz_target_workspacesservice_authorizeiprules.CreateAuthorizeiprulesTool(cfg),
		tools_x_amz_target_workspacesservice_describeconnectionaliaspermissions.CreateDescribeconnectionaliaspermissionsTool(cfg),
		tools_x_amz_target_workspacesservice_deleteconnectionalias.CreateDeleteconnectionaliasTool(cfg),
		tools_x_amz_target_workspacesservice_describeipgroups.CreateDescribeipgroupsTool(cfg),
		tools_x_amz_target_workspacesservice_rebootworkspaces.CreateRebootworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_deletetags.CreateDeletetagsTool(cfg),
		tools_x_amz_target_workspacesservice_copyworkspaceimage.CreateCopyworkspaceimageTool(cfg),
		tools_x_amz_target_workspacesservice_importworkspaceimage.CreateImportworkspaceimageTool(cfg),
		tools_x_amz_target_workspacesservice_createconnectclientaddin.CreateCreateconnectclientaddinTool(cfg),
		tools_x_amz_target_workspacesservice_modifyworkspaceproperties.CreateModifyworkspacepropertiesTool(cfg),
		tools_x_amz_target_workspacesservice_modifyworkspacestate.CreateModifyworkspacestateTool(cfg),
		tools_x_amz_target_workspacesservice_createupdatedworkspaceimage.CreateCreateupdatedworkspaceimageTool(cfg),
		tools_x_amz_target_workspacesservice_createworkspaces.CreateCreateworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_describeaccount.CreateDescribeaccountTool(cfg),
		tools_x_amz_target_workspacesservice_createworkspaceimage.CreateCreateworkspaceimageTool(cfg),
		tools_x_amz_target_workspacesservice_modifyworkspaceaccessproperties.CreateModifyworkspaceaccesspropertiesTool(cfg),
		tools_x_amz_target_workspacesservice_describeworkspaces.CreateDescribeworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_describeclientbranding.CreateDescribeclientbrandingTool(cfg),
		tools_x_amz_target_workspacesservice_startworkspaces.CreateStartworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_createstandbyworkspaces.CreateCreatestandbyworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_importclientbranding.CreateImportclientbrandingTool(cfg),
		tools_x_amz_target_workspacesservice_deleteipgroup.CreateDeleteipgroupTool(cfg),
		tools_x_amz_target_workspacesservice_revokeiprules.CreateRevokeiprulesTool(cfg),
		tools_x_amz_target_workspacesservice_updateconnectclientaddin.CreateUpdateconnectclientaddinTool(cfg),
		tools_x_amz_target_workspacesservice_deleteconnectclientaddin.CreateDeleteconnectclientaddinTool(cfg),
		tools_x_amz_target_workspacesservice_describeconnectionaliases.CreateDescribeconnectionaliasesTool(cfg),
		tools_x_amz_target_workspacesservice_describeworkspacebundles.CreateDescribeworkspacebundlesTool(cfg),
		tools_x_amz_target_workspacesservice_migrateworkspace.CreateMigrateworkspaceTool(cfg),
		tools_x_amz_target_workspacesservice_deleteworkspacebundle.CreateDeleteworkspacebundleTool(cfg),
		tools_x_amz_target_workspacesservice_listavailablemanagementcidrranges.CreateListavailablemanagementcidrrangesTool(cfg),
		tools_x_amz_target_workspacesservice_modifycertificatebasedauthproperties.CreateModifycertificatebasedauthpropertiesTool(cfg),
		tools_x_amz_target_workspacesservice_deleteworkspaceimage.CreateDeleteworkspaceimageTool(cfg),
		tools_x_amz_target_workspacesservice_rebuildworkspaces.CreateRebuildworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_registerworkspacedirectory.CreateRegisterworkspacedirectoryTool(cfg),
		tools_x_amz_target_workspacesservice_modifyselfservicepermissions.CreateModifyselfservicepermissionsTool(cfg),
		tools_x_amz_target_workspacesservice_describetags.CreateDescribetagsTool(cfg),
		tools_x_amz_target_workspacesservice_stopworkspaces.CreateStopworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_describeworkspacesnapshots.CreateDescribeworkspacesnapshotsTool(cfg),
		tools_x_amz_target_workspacesservice_modifysamlproperties.CreateModifysamlpropertiesTool(cfg),
		tools_x_amz_target_workspacesservice_describeworkspaceimagepermissions.CreateDescribeworkspaceimagepermissionsTool(cfg),
		tools_x_amz_target_workspacesservice_modifyaccount.CreateModifyaccountTool(cfg),
		tools_x_amz_target_workspacesservice_associateipgroups.CreateAssociateipgroupsTool(cfg),
		tools_x_amz_target_workspacesservice_describeworkspacedirectories.CreateDescribeworkspacedirectoriesTool(cfg),
		tools_x_amz_target_workspacesservice_deregisterworkspacedirectory.CreateDeregisterworkspacedirectoryTool(cfg),
		tools_x_amz_target_workspacesservice_describeclientproperties.CreateDescribeclientpropertiesTool(cfg),
		tools_x_amz_target_workspacesservice_updateworkspaceimagepermission.CreateUpdateworkspaceimagepermissionTool(cfg),
		tools_x_amz_target_workspacesservice_describeaccountmodifications.CreateDescribeaccountmodificationsTool(cfg),
		tools_x_amz_target_workspacesservice_createtags.CreateCreatetagsTool(cfg),
		tools_x_amz_target_workspacesservice_terminateworkspaces.CreateTerminateworkspacesTool(cfg),
		tools_x_amz_target_workspacesservice_deleteclientbranding.CreateDeleteclientbrandingTool(cfg),
		tools_x_amz_target_workspacesservice_disassociateipgroups.CreateDisassociateipgroupsTool(cfg),
		tools_x_amz_target_workspacesservice_createconnectionalias.CreateCreateconnectionaliasTool(cfg),
		tools_x_amz_target_workspacesservice_updaterulesofipgroup.CreateUpdaterulesofipgroupTool(cfg),
		tools_x_amz_target_workspacesservice_restoreworkspace.CreateRestoreworkspaceTool(cfg),
		tools_x_amz_target_workspacesservice_disassociateconnectionalias.CreateDisassociateconnectionaliasTool(cfg),
		tools_x_amz_target_workspacesservice_describeworkspaceimages.CreateDescribeworkspaceimagesTool(cfg),
		tools_x_amz_target_workspacesservice_createipgroup.CreateCreateipgroupTool(cfg),
		tools_x_amz_target_workspacesservice_associateconnectionalias.CreateAssociateconnectionaliasTool(cfg),
		tools_x_amz_target_workspacesservice_describeconnectclientaddins.CreateDescribeconnectclientaddinsTool(cfg),
		tools_x_amz_target_workspacesservice_updateconnectionaliaspermission.CreateUpdateconnectionaliaspermissionTool(cfg),
	}
}
